modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mynx"
version = "${version}"
displayName = "MYNX"
authors = "veronoicc"
description = '''
The official companion mod for the MYNX Server Scanner: find new servers without ever leaving Minecraft!
'''
logoFile = "assets/mynx/icon.png"

[[dependencies.mynx]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mynx]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mynx]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"